# <span style="color:Thistle">Comprendiendo los tipos de datos en Python</span>

#### <span style="color:beige">Sesión 2</span>
---



## Arrays de tipo fijo en Python

Python ofrece varias opciones para almacenar datos en búferes de datos eficientes de tipo fijo. El módulo integrado `array` puede usarse para crear arrays densode un tipo uniforme:

In [17]:
import array
lista_enteros = list(range(10))
arr_enteros = array.array('i', lista_enteros)
arr_enteros

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Aquí `'i'` es un código de tipo que indica que el contenido son enteros (`int`)

Sin embargo, mucho más útil es el objeto `np.array` del paquete NumPy. Mientras que el objeto `array` de Python proporciona almacenamiento eficiente de datos basados en arrays, <span style="color:Gold">NumPy añade *operaciones* eficientes sobre esos datos</span>.

Y por eso lo usaremos en análisis de datos.

Vamos a crear arrays con NumPy.

Comenzaremos con la importación estándar de NumPy, bajo el alias `np`:

In [18]:
import numpy as np

---
## Creación de Arrays a partir de Listas de Python

En primer lugar, podemos usar `np.array` para crear arrays a partir de listas de Python:

In [20]:
# array de enteros:
np.array([1, 4, 2, 5, 6])

array([1, 4, 2, 5, 6])

Recuerda que, a diferencia de las listas de Python, NumPy está limitado a arrays que contienen todos el mismo tipo. Si los tipos no coinciden, <span style="color:Gold">NumPy realizará un upgrade/promoción</span> de tipo (*upcast*) si es posible (aquí, los enteros se upgradean a punto flotante):

In [21]:
# mezcla de entero y flotante --> se promueve todo a flotante
np.array([3.14, 4.2, 2, 3])

array([3.14, 4.2 , 2.  , 3.  ])

Si queremos establecer explícitamente el tipo de datos del array resultante, podemos usar el argumento `dtype`:

In [7]:
# forzar tipo flotante de 32 bits
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

<div class="alert alert-block alert-success">
<b>Nota:</b> Es clave familiarizarnos con el argumento dtype.
</div>

---
## Creación de arrays desde cero

Especialmente para arrays grandes, es más eficiente crear arrays desde cero utilizando las funciones de NumPy. Aquí hay varios ejemplos:

In [8]:
# Crear un array de enteros de longitud 10 relleno de ceros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
# Crear un array de punto flotante de 20 relleno de unos
np.ones(20, dtype=float)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [11]:
# Crear un array 3x5 relleno con el valor 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [12]:
# Crear un array relleno con una secuencia lineal
# Empezando en 0, terminando en 20, con paso de 2
# (similar a la función integrada range())
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
# Crear un array de cinco valores entre 0 y 1 sepasrados por la misma distancia
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
# Crear un array de tam 5 de valores aleatorios con distribución uniforme de 0 a 1
np.random.random(5)

array([0.71408106, 0.86383935, 0.68114461, 0.92081734, 0.87532759])

<div class="alert alert-block alert-info">
<b>Pregunta:</b> ¿Qué son valores normalizados?
</div>


In [14]:
# Crear un array 3x3 de valores aleatorios con distribución normal
# con media 0 y desviación típica 1
np.random.normal(0, 1, (3, 3))

array([[-0.47625829, -0.00610643, -0.81014065],
       [-0.53291225, -1.17376377, -1.09989395],
       [-0.07749485,  0.04616588,  1.25766884]])

<div class="alert alert-block alert-info">
<b>Pregunta:</b> ¿Qué es una distribución normal?
</div>

In [22]:
# Crear un array de tam 5 de enteros aleatorios en el intervalo [0, 10)
np.random.randint(0, 10, 100)

array([5, 5, 4, 7, 2, 9, 9, 9, 1, 9, 2, 6, 3, 0, 1, 5, 0, 7, 5, 1, 7, 5,
       0, 7, 7, 1, 2, 8, 9, 3, 9, 4, 3, 7, 6, 5, 1, 6, 9, 4, 1, 7, 1, 7,
       6, 4, 2, 8, 7, 5, 2, 7, 7, 0, 2, 7, 6, 1, 3, 2, 1, 8, 5, 6, 9, 3,
       7, 8, 4, 1, 6, 8, 0, 1, 0, 1, 6, 9, 9, 8, 0, 2, 1, 6, 5, 0, 3, 9,
       2, 8, 0, 6, 1, 0, 7, 1, 7, 8, 4, 5], dtype=int32)

---
## Tipos de datos estándar de NumPy

Los arrays NumPy contienen valores de un único tipo, por lo que es importante conocer en detalle esos tipos y sus limitaciones. NumPy está desarrollado en C.

Los tipos de datos estándar de NumPy se listan en la siguiente tabla. Ten en cuenta que al construir un array pueden especificarse mediante una cadena de texto:

```python
np.zeros(10, dtype='int16')
```

O usando el objeto NumPy asociado:

```python
np.zeros(10, dtype=np.int16)
```

| Tipo de dato | Descripción |
|---|---|
| `bool_` | Booleano (True o False) almacenado como un byte |
| `int_` | Tipo entero por defecto (igual que `long` en C; normalmente `int64` o `int32`) |
| `intc` | Idéntico a `int` en C (normalmente `int32` o `int64`) |
| `intp` | Entero usado para indexación (igual que `ssize_t` en C; normalmente `int32` o `int64`) |
| `int8` | Byte (-128 a 127) |
| `int16` | Entero (-32768 a 32767) |
| `int32` | Entero (-2147483648 a 2147483647) |
| `int64` | Entero (-9223372036854775808 a 9223372036854775807) |
| `uint8` | Entero sin signo (0 a 255) |
| `uint16` | Entero sin signo (0 a 65535) |
| `uint32` | Entero sin signo (0 a 4294967295) |
| `uint64` | Entero sin signo (0 a 18446744073709551615) |
| `float_` | Abreviatura de `float64` |
| `float16` | Flotante de media precisión: bit de signo, 5 bits de exponente, 10 bits de mantisa |
| `float32` | Flotante de simple precisión: bit de signo, 8 bits de exponente, 23 bits de mantisa |
| `float64` | Flotante de doble precisión: bit de signo, 11 bits de exponente, 52 bits de mantisa |
| `complex_` | Abreviatura de `complex128` |
| `complex64` | Número complejo representado por dos flotantes de 32 bits |
| `complex128` | Número complejo representado por dos flotantes de 64 bits |

<div class="alert alert-block alert-info">
<b>Pregunta:</b> ¿Cual es el tipo por defecto de int y float en lenguajes como C++, Java, C#?
</div>

<div class="alert alert-block alert-info">
<b>Pregunta:</b> ¿Qué representa el 8 en int8?
</div>

<div class="alert alert-block alert-info">
<b>Pregunta:</b> ¿Qué diferencia hay entre intX y uintX?
</div>

