# Máscaras Booleanas en NumPy

---

In [3]:
import numpy as np
print('NumPy', np.__version__)

NumPy 2.4.2


---
## BLOQUE 1 — Filtrado simple con condición única

---
### Ejercicio 1 — Temperaturas por encima del umbral

**Enunciado:**  
Una estación meteorológica registró las temperaturas diarias (°C) durante dos semanas.  
Filtra y devuelve solo las temperaturas que superan los 30°C (ola de calor).

**Ten en cuenta:**
- Una máscara booleana es un array de `True/False` del mismo tamaño.
- Puedes crear una con `array > valor`.
- Aplica la máscara al array original usando corchetes: `array[mascara]`.


In [13]:
temperaturas = np.array([22.1, 31.5, 28.4, 35.2, 19.8, 33.0, 27.6,
                         30.1, 29.9, 36.4, 21.3, 32.8, 18.5, 34.7])
mascara_30 = temperaturas > 30
oladecalor = temperaturas[mascara_30]
print(oladecalor)

[31.5 35.2 33.  30.1 36.4 32.8 34.7]


**Variante extra:** Calcula también el promedio de temperaturas durante los días de ola de calor.

---
### Ejercicio 2 — Notas de estudiantes aprobados

**Enunciado:**  
Un profesor tiene las notas finales de 12 estudiantes (escala 0-10).  
Extrae las notas de quienes aprobaron (nota >= 5) y cuenta cuántos suspendieron.

**Ten en cuenta:**
- `~mascara` invierte una máscara booleana (`True` <-> `False`).
- `.sum()` sobre una máscara cuenta los `True`.


In [22]:
notas = np.array([7.5, 3.2, 9.1, 4.8, 6.0, 2.5, 8.3, 5.0, 1.9, 7.7, 4.1, 6.5])

mascara_nota5 = notas >= 5
aprovados = notas[mascara_nota5]
suspendidos = (~mascara_nota5).sum()
print(aprovados)
print(suspendidos)

[7.5 9.1 6.  8.3 5.  7.7 6.5]
5


**Variante extra:** Añade una segunda condición: extrae solo los sobresalientes (nota >= 9).

---
### Ejercicio 3 — Stock de productos agotados

**Enunciado:**  
Un almacén registra el stock de 10 productos.  
Obtén los índices de los productos agotados (stock = 0) para saber qué reabastecer.

**Ten en cuenta:**
- `np.where(condición)` devuelve una tupla con los **índices** donde la condición es `True`.
- `array == valor` crea una máscara de igualdad exacta.


In [28]:
stock = np.array([120, 0, 45, 0, 300, 0, 18, 0, 77, 0])
mascara_0 = stock == 0

indices_agotados = np.where(mascara_0)[0]
print(indices_agotados)

[1 3 5 7 9]


**Variante extra:** Identifica también los productos con stock crítico (mayor que 0 pero menor que 20).

---
### Ejercicio 4 — Ventas por debajo del objetivo

**Enunciado:**  
Un equipo comercial tiene registradas las ventas mensuales en miles de euros.  
El objetivo mensual es 50 000 EUR. Devuelve los valores que **no** alcanzaron el objetivo y calcula el déficit total.

**Ten en cuenta:**
- El déficit de cada mes fallido es `objetivo - venta`.
- Puedes hacer operaciones aritméticas sobre valores filtrados.


In [ ]:
ventas = np.array([48.2, 63.5, 41.0, 55.8, 38.9, 70.2, 49.5, 52.1, 44.7, 60.0, 37.3, 58.6])
objetivo = 50.0 

noalcanzan = ventas < objetivo
ventas_fallidas = ventas[noalcanzan]

deficit = objetivo - ventas

print(ventas_fallidas,deficit.sum())

[48.2 41.  38.9 49.5 44.7 37.3] -19.800000000000004


**Variante extra:** Calcula el porcentaje de meses que superaron el objetivo.

---
## BLOQUE 2 — Condiciones combinadas con &, | y ~

---
### Ejercicio 5 — Rango de temperatura ideal

**Enunciado:**  
Una bodega necesita mantener la temperatura entre 12°C y 18°C.  
Filtra las lecturas que caen dentro del rango aceptable usando `&`.

**Ten en cuenta:**
- Cuando combinas dos máscaras con `&`, **cada condición debe ir entre paréntesis**.
- `(array > a) & (array < b)` es la forma correcta.


In [ ]:
lecturas = np.array([10.5, 13.2, 21.0, 15.8, 8.4, 17.9, 12.0, 19.3, 14.6, 11.1, 18.0, 22.5])

**Variante extra:** Separa las lecturas fuera de rango en dos grupos: las que están por debajo y las que están por encima.

---
### Ejercicio 6 — Detección de valores extremos

**Enunciado:**  
Un sensor de presión industrial registra lecturas en bar.  
Considera extremo cualquier valor menor de 5 bar **o** mayor de 95 bar. Identifica y cuenta los outliers.

**Ten en cuenta:**
- Cuando la condición es 'A **o** B', usa `|` (OR lógico).
- Los paréntesis son obligatorios en cada subcondición.


In [ ]:
presiones = np.array([45.2, 3.1, 78.4, 97.6, 52.0, 1.5, 60.3, 88.9,
                      100.2, 40.0, 4.9, 73.5, 50.0, 96.1, 55.8])

**Variante extra:** Calcula la media y desviación típica **excluyendo** los outliers.

---
### Ejercicio 7 — Filtro de candidatos en proceso de selección

**Enunciado:**  
Tenemos dos arrays paralelos: puntuaciones técnicas y de entrevista (0-100).  
Un candidato pasa si tiene técnica >= 70 **y** entrevista >= 60,  
**o** si tiene técnica >= 90 (candidato excepcional, pasa directamente).

**Ten en cuenta:**
- Puedes combinar más de dos condiciones: `(A & B) | C`.
- Respeta siempre los paréntesis para controlar la precedencia.


In [ ]:
tecnica    = np.array([85, 55, 92, 70, 68, 91, 74, 60, 88, 45, 95, 72])
entrevista = np.array([75, 80, 50, 65, 90, 85, 55, 70, 72, 60, 40, 88])

**Variante extra:** Añade una condición de rechazo automático: entrevista < 40 descarta al candidato sin importar su nota técnica.

---
### Ejercicio 8 — Análisis de edades en un censo

**Enunciado:**  
Un censo recoge edades de habitantes. Separa la población en tres grupos:
- **Menores:** < 18 años  
- **Adultos:** 18 a 64 años (inclusive)  
- **Mayores:** >= 65 años

**Ten en cuenta:**
- Crea tres máscaras separadas, una por grupo.
- Comprueba que son mutuamente excluyentes sumando sus `.sum()`.


In [ ]:
edades = np.array([8, 34, 72, 15, 45, 67, 3, 29, 55, 80, 18, 63, 64, 65, 17, 22])

**Variante extra:** Calcula la edad media de cada grupo usando la máscara correspondiente.

---
## BLOQUE 4 — Reemplazo de valores usando máscaras

---
### Ejercicio 9 — Censurar valores extremos (clipping manual)

**Enunciado:**  
Un sensor de temperatura tiene lecturas erróneas: valores por debajo de -20°C o por encima de 60°C son imposibles.  
Reemplaza esos valores con `np.nan` para marcarlos como no válidos.

**Ten en cuenta:**
- `array[mascara] = valor` reemplaza **in place** (modifica el array original).
- `np.nan` solo funciona con arrays de tipo `float`, no `int`.
- Es buena práctica trabajar sobre una copia: `array.copy()`.


In [5]:
temps_sensor = np.array([-25.0, 18.5, 62.3, 30.0, -22.1, 45.6, 15.0,
                          70.0, 28.9, -30.0, 50.2, 55.5], dtype=float)
temps_limpio = temps_sensor.copy()
fuera_rango = (temps_sensor < -20) | (temps_sensor > 60)

print("Lecturas erroneas=",fuera_rango.sum())
temps_limpio[fuera_rango] = np.nan
print(temps_limpio)

Lecturas erroneas= 5
[ nan 18.5  nan 30.   nan 45.6 15.   nan 28.9  nan 50.2 55.5]


**Variante extra:** En lugar de NaN, reemplaza los valores erróneos con la media de los valores válidos.

---
### Ejercicio 10 — Sistema de calificaciones: convertir a letra

**Enunciado:**  
Convierte notas numéricas a letras usando reemplazos con máscaras:
- **F:** < 5 | **D:** 5-6.4 | **C:** 6.5-7.4 | **B:** 7.5-8.4 | **A:** 8.5-10

**Ten en cuenta:**
- Crea un array de strings: `np.full(shape, '?', dtype='U1')`.
- Aplica las máscaras en cualquier orden (son mutuamente excluyentes).


In [10]:
puntos = np.array([3.2, 7.8, 5.5, 9.1, 6.5, 8.5, 4.9, 7.0, 8.0, 10.0, 6.0, 9.8])

letras = np.full(puntos.shape, '?',dtype='U1')
mascara_f = puntos < 5
mascara_d = (puntos >= 5) & (puntos <= 6.4)
mascara_c = (puntos >= 6.5) & (puntos <= 7.4)
mascara_b = (puntos >= 7.5) & (puntos <= 8.4)
mascara_a = (puntos >= 8.5) & (puntos <= 10)

letras[mascara_f] = "F"
letras[mascara_d] = "D"
letras[mascara_c] = "C"
letras[mascara_b] = "B"
letras[mascara_a] = "A"

print(letras)

['F' 'B' 'D' 'A' 'C' 'A' 'F' 'C' 'B' 'A' 'D' 'A']


**Variante extra:** Añade 'matricula de honor': nota >= 9.5 -> letra 'MH' (necesitarás `dtype='U2'`).

---
### Ejercicio 11 — Normalización condicional de datos de ventas

**Enunciado:**  
Un dataset tiene valores negativos (devoluciones) y positivos (ventas).  
Normaliza **solo** los valores positivos al rango [0, 1] usando la fórmula min-max, dejando los negativos intactos.

**Ten en cuenta:**
- Extrae los valores positivos con la máscara, calcula min y max sobre ellos.
- Fórmula min-max: `(x - min) / (max - min)`.
- Recuerda asignar el resultado de vuelta al array con la misma máscara.


In [ ]:
datos_ventas = np.array([120.0, -30.0, 450.0, -15.0, 300.0, -80.0,
                          600.0, 80.0, -5.0, 200.0, -50.0, 500.0])

**Variante extra:** Aplica la normalización también a los negativos pero en el rango [-1, 0].

---
### Ejercicio 12 — Imputación de valores faltantes en encuesta

**Enunciado:**  
Una encuesta de satisfacción (1-5) tiene respuestas faltantes representadas como 0.  
Imputa los valores faltantes con: la mediana de las respuestas válidas.

**Ten en cuenta:**
- Usa la máscara para filtrar los válidos antes de calcular estadísticas.
- Para la moda: `np.bincount(array)` cuenta frecuencias; `np.argmax()` da el índice del máximo.


In [ ]:
respuestas = np.array([4, 0, 3, 5, 0, 2, 4, 0, 5, 3, 0, 4, 1, 0, 3])

**Variante extra:** Imputa usando la mediana de los vecinos más cercanos (+-2 posiciones).